### ISSUE TITLE
要用哪个账号才能登录啊

### ISSUE THREAD

**Issue by excitedhaha** [lzan13/EaseUICustomer#2]
为什么我用自己的环信账号无法登录

**Comment by lzan13** [comment]
这个要在配置文件配置下你自己的appkey，用你自己的appkey下的im账户登录

**Comment by zhangcola** [comment]
用了，也不行，还是提示登录账号密码错误

**Comment by lzan13** [comment]
确认下appkey是不是你当前账户的appkey以及看看初始化时是否也有设置appkey

**Comment by zhangcola** [comment]
配置和代码里面的APPKey已经改了，现在可以实现登录；但是聊天发送消息，环信这边的客服客户端也没能收到消息，实现不了消息互发，请问还有哪里需要修改么？

**Comment by lzan13** [comment]
客服客户端？要实现联系客服的话，你得在客服后台进行配置关联自己的appkey和im账户，看看你做了这步没
